# Generated by Django 2.2 on 2020-11-06 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201106_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_preview',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Предварительный просмотр статьи'),
            preserve_default=False,
        ),
    ]
