# Generated by Django 2.2 on 2020-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201106_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_preview',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания статьи'),
        ),
    ]
